# Generated by Django 2.1.4 on 2018-12-17 10:35

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Customer Name')),
                ('dob', models.DateField()),
                ('age', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('no_children', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)])),
                ('no_children_drive', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)])),
                ('income', models.IntegerField(default=0)),
                ('parents_alive', models.BooleanField(default=False)),
                ('home_estimate', models.IntegerField(default=0)),
                ('marriage_status', models.CharField(choices=[('Unmarried', 'Unmarried'), ('Married', 'Married')], max_length=100, verbose_name='Marriage Status')),
                ('gender', models.CharField(choices=[('Female', 'Female'), ('Male', 'Male')], max_length=100)),
                ('education', models.CharField(choices=[('Less than High School', 'Less than High School'), ('High School', 'High School'), ('Bachelors', 'Bachelors'), ('Masters', 'Masters'), ('PhD', 'PhD')], max_length=100)),
                ('occupation', models.CharField(choices=[('Manager', 'Manager'), ('Doctor', 'Doctor'), ('Student', 'Student'), ('Blue Collar', 'Blue Collar'), ('Lawyer', 'Lawyer'), ('Clerical', 'Clerical'), ('Professional', 'Professional'), ('Home', 'Home')], max_length=100)),
                ('avg_travel_time', models.IntegerField(default=0)),
                ('car_use', models.CharField(choices=[('Commercial', 'Commercial'), ('Private', 'Private')], max_length=100)),
                ('car_type', models.CharField(choices=[('Van', 'Van'), ('Panel Truck', 'Panel Truck'), ('Minivan', 'Minivan'), ('Sports', 'Sports'), ('SUV', 'SUV'), ('Pickup', 'Pickup')], max_length=100)),
                ('car_color_red', models.BooleanField(default=False)),
                ('car_age', models.IntegerField(default=0)),
                ('urbanicity', models.CharField(choices=[('Rural', 'Rural'), ('Urban', 'Urban')], max_length=100)),
                ('risk', models.FloatField(default=0.0, validators=[django.core.validators.MaxValueValidator(1.0)])),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.CompanyProfile')),
            ],
        ),
    ]
