# Generated by Django 2.1.4 on 2018-12-30 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20181227_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='car_use',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customer',
            name='gender',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customer',
            name='home_estimate',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='customer',
            name='income',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='customer',
            name='insured_value',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='customer',
            name='marriage_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customer',
            name='prev_insurance_amt',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='customer',
            name='urbanicity',
            field=models.BooleanField(default=False),
        ),
    ]
