# Generated by Django 2.1.4 on 2019-01-02 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20181230_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='home_estimate',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='customer',
            name='income',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='customer',
            name='insured_value',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='customer',
            name='risk',
            field=models.FloatField(default=0.0),
        ),
    ]
